# the name of this file must be exactly like the name of the application

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: identity
          uri: lb://IDENTITY
          predicates:
            - Path=/api/v1/**

        - id: identity-openapi
          uri: lb://IDENTITY
          predicates:
            - Path=/v3/api-docs/identity
          filters:
            - SetPath=/v3/api-docs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Identity
        url: /v3/api-docs/identity

logging:
  level:
    org.springframework.cloud.gateway: INFO

security:
  jwt:
    secret: "n82dHJjidj3j8DH83dhkjmaO83NOUh_d772GHDS1D3"
    ttl: 3600 # seconds