# the name of this file must be exactly like the name of the application

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: ${IDENTITY_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    secret: ${JWT_SECRET}
    ttl: ${JWT_TTL_SECONDS}