# the name of this file must be exactly like the name of the application

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/integrations_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

telegram:
  bot-api-url: https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}

security:
  internal:
    token: "super-secret-internal-token"

alice:
  oauth:
    client-id: chore-manager-alice
    client-secret: super-secret-value