# the name of this file must be exactly like the name of the application

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: ${INTEGRATIONS_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

telegram:
  bot-api-url: https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}

security:
  internal:
    token: ${INTERNAL_TOKEN}

alice:
  oauth:
    client-id: ${ALICE_CLIENT_ID}
    client-secret: ${ALICE_CLIENT_SECRET}