# the name of this file must be exactly like the name of the application

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: ${TASK_MANAGEMENT_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

security:
  internal:
    token: ${INTERNAL_TOKEN}